[package]
name = "reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
opencv = "0.82.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
